name: bird-ringing

services:

  database-init:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ringdb
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-pass
      DB_ADMIN_PASSWORD_FILE: /run/secrets/db-admin-pass
      DB_USER_PASSWORD_FILE: /run/secrets/db-user-pass
    volumes:
      - database-vol:/var/lib/postgresql
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    secrets:
      - postgres-pass
      - db-admin-pass
      - db-user-pass
    command: ["docker-ensure-initdb.sh"]
    restart: "no"

  database:
    image: postgres:18-alpine
    volumes:
      - database-vol:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      database-init:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
      target: prod
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    volumes:
      - frontend-vol:/vol
    depends_on:
      database:
        condition: service_healthy

  backend-init:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
      target: prod
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      POSTGRES_USER: db_admin
      SERVICE_MODE: production-init
      POSTGRES_PASSWORD_FILE: /run/secrets/db-admin-pass
      DJANGO_SECRET_FILE: /run/secrets/django-secret-key
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - db-admin-pass
      - django-secret-key

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
      target: prod
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      POSTGRES_USER: db_user
      SERVICE_MODE: production
      POSTGRES_PASSWORD_FILE: /run/secrets/db-user-pass
      DJANGO_SECRET_FILE: /run/secrets/django-secret-key
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-}
      LICENSE_CARD_FILE: ${LICENSE_CARD_FILE:-}
      LICENSE_CARD_FILE_BACK: ${LICENSE_CARD_BACK_FILE:-}
    volumes:
      - backend-vol:/vol
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=5", "http://backend:8000/api/system/health/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      backend-init:
        condition: service_completed_successfully
    secrets:
      - db-user-pass
      - django-secret-key

  proxy:
    image: caddy:2-alpine
    ports:
      - 127.0.0.1:3210:80
    volumes:
      - ./caddy:/etc/caddy:ro
      - frontend-vol:/frontend:ro
      - backend-vol:/backend:ro
      - proxy-vol:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=5", "http://proxy/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      frontend:
        condition: service_completed_successfully
      backend:
        condition: service_healthy

volumes:
  database-vol:
  frontend-vol:
  backend-vol:
  proxy-vol:

secrets:
  postgres-pass:
    file: ./secrets/postgres-pass.txt
  db-admin-pass:
    file: ./secrets/db-admin-pass.txt
  db-user-pass:
    file: ./secrets/db-user-pass.txt
  django-secret-key:
    file: ./secrets/django-secret-key.txt
