services:

  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/app
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://frontend:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend-init:
    build:
      target: dev
    environment:
      SERVICE_MODE: development-init
    volumes:
      - ./backend:/app

  backend:
    build:
      target: dev
    environment:
      SERVICE_MODE: development
    volumes:
      - ./backend:/app

  proxy:
    environment:
      SERVICE_MODE: development
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy

