name: bird-ringing

services:

  database:
    image: postgres:17-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/17/docker
      POSTGRES_PASSWORD_FILE: /run/secrets/db-root-pass
      DB_ENV_FILE: /run/secrets/db-env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database-vol:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    secrets:
      - db-root-pass
      - db-env

volumes:
  database-vol:

secrets:
  db-root-pass:
    file: ./secrets/db-root-pass.txt
  db-env:
    file: ./secrets/database.env
