# Generated by Django 6.0.3 on 2026-03-23 15:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=2048)),
                ('first_name', models.CharField(blank=True, default='', max_length=1024)),
                ('last_name', models.CharField(blank=True, default='', max_length=1024)),
                ('type', models.PositiveIntegerField(choices=[(0, 'person'), (1, 'station')])),
                ('sex', models.PositiveIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'undisclosed'), (4, 'n/a')])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.PositiveIntegerField(choices=[(0, 'unknown'), (1, 'sv'), (2, 'en')], default=0)),
                ('phone_number1', models.CharField(blank=True, default='', max_length=128)),
                ('phone_number2', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=2048)),
                ('alternative_email', models.EmailField(blank=True, default='', max_length=2048)),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('co_address', models.CharField(blank=True, default='', max_length=512)),
                ('postal_code', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=256)),
                ('country', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActorImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('fingerprint', models.CharField(max_length=40, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('report_status', models.PositiveIntegerField(choices=[(1, 'yes'), (2, 'no'), (3, 'incomplete')])),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveIntegerField(choices=[(1, 'license-delivery'), (2, 'license-update')])),
                ('status', models.PositiveIntegerField(choices=[(1, 'sent'), (2, 'received'), (3, 'bounced'), (4, 'failed')])),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication', to='licensing.actor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication', to='licensing.license')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_permanent', models.BooleanField()),
                ('type', models.PositiveIntegerField(choices=[(1, 'document'), (2, 'license'), (3, 'permit')])),
                ('data', models.BinaryField(null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=2048)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='licensing.actor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='documents',
            field=models.ManyToManyField(blank=True, to='licensing.licensedocument'),
        ),
        migrations.CreateModel(
            name='LicenseImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('fingerprint', models.CharField(max_length=40, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.license')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicensePermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicensePermissionProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licensing.licensepermissiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mnr', models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=4)])),
                ('status', models.PositiveIntegerField(choices=[(1, 'active'), (2, 'inactive'), (3, 'terminated')])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('latest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='licensing.license')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='licensedocument',
            name='license_sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='licensing.licensesequence'),
        ),
        migrations.AddField(
            model_name='license',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='licensing.licensesequence'),
        ),
        migrations.CreateModel(
            name='LicenseSequenceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('fingerprint', models.CharField(max_length=40, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.licensesequence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermitDnr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dnr_number', models.CharField(max_length=64)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=512)),
                ('scientific_code', models.CharField(blank=True, default='', max_length=128)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='LicensePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='licensing.license')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('properties', models.ManyToManyField(blank=True, to='licensing.licensepermissionproperty')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licensing.licensepermissiontype')),
                ('species_list', models.ManyToManyField(blank=True, to='licensing.species')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('fingerprint', models.CharField(max_length=40, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.species')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mednr', models.CharField(blank=True, default='', max_length=4, validators=[django.core.validators.MinLengthValidator(limit_value=4)])),
                ('role', models.PositiveIntegerField(choices=[(1, 'ringer'), (2, 'associate ringer'), (3, 'affiliate'), (4, 'communication')])),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.actor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='licensing.license')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'role', 'license'), name='unique-actors-for-role-and-license'), models.UniqueConstraint(fields=('mednr', 'license'), name='unique-mednr-for-license')],
            },
        ),
        migrations.AddConstraint(
            model_name='licensedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_permanent', False)), fields=('license_sequence', 'actor', 'type', 'fingerprint'), name='unique_document_per_license_sequence__actor__type__fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(fields=('version', 'sequence'), name='version-sequence-unique'),
        ),
        migrations.AddIndex(
            model_name='permitdnr',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='licensing_p_is_acti_eb141a_idx'),
        ),
        migrations.AddConstraint(
            model_name='permitdnr',
            constraint=models.UniqueConstraint(fields=('starts_at',), name='unique_permit_dnr_starts_at'),
        ),
    ]
