# Generated by Django 6.0.3 on 2026-03-26 12:15

import licensing.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensepermission',
            name='ends_at',
            field=licensing.models.MonthDayField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensepermission',
            name='starts_at',
            field=licensing.models.MonthDayField(blank=True, null=True),
        ),
    ]
