# Generated by Django 6.0.3 on 2026-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_alter_licensepermission_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensesequence',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'active'), (2, 'paused'), (3, 'terminated')]),
        ),
    ]
