# Generated by Django 5.2.7 on 2026-01-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_alter_actor_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
    ]
