# Generated by Django 6.0.3 on 2026-05-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_alter_licensesequence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='language',
            field=models.PositiveIntegerField(choices=[(0, 'Unknown'), (1, 'Swedish'), (2, 'English'), (3, 'Albanian'), (4, 'Arabic'), (5, 'Azerbaijani'), (6, 'Basque'), (7, 'Belarusian'), (8, 'Bosnian'), (9, 'Bulgarian'), (10, 'Catalan'), (11, 'Croatian'), (12, 'Czech'), (13, 'Danish'), (14, 'Dutch'), (15, 'Estonian'), (16, 'Finnish'), (17, 'French'), (18, 'Georgian'), (19, 'German'), (20, 'Greek'), (21, 'Hebrew'), (22, 'Hungarian'), (23, 'Icelandic'), (24, 'Italian'), (25, 'Kazakh'), (26, 'Latvian'), (27, 'Lithuanian'), (28, 'Macedonian'), (29, 'Maltese'), (30, 'Montenegrin'), (31, 'Norwegian'), (32, 'Polish'), (33, 'Portuguese'), (34, 'Romanian'), (35, 'Russian'), (36, 'Serbian'), (37, 'Slovak'), (38, 'Slovenian'), (39, 'Spanish'), (40, 'Turkish'), (41, 'Ukrainian')], default=0),
        ),
    ]
