# Generated by Django 6.0.1 on 2026-01-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_alter_species_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedocument',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='licensedocument',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
