# Generated by Django 6.0.3 on 2026-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_alter_actor_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
