# Generated by Django 6.0.1 on 2026-01-18 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_licensedocument_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='licensedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('license', 'actor', 'type'), name='unique_current_doc_per_license_actor_type'),
        ),
    ]
