# Generated by Django 6.0.3 on 2026-06-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_alter_license_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensepermission',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='licenserelation',
            options={'ordering': ['pk']},
        ),
    ]
