# Generated by Django 6.0.3 on 2026-09-30 07:53

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_alter_licensepermission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='ends_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='LocationPresetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='licensing.locationpresetgroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='locationpresetgroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique-name'),
        ),
        migrations.AddConstraint(
            model_name='locationpreset',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('group'), name='unique-name-within-group'),
        ),
    ]
