# Generated by Django 6.0.1 on 2026-02-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_licensedocument_unique_current_doc_per_license_actor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
