# Generated by Django 6.0.1 on 2026-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_licensedocument_unique_current_doc_per_license_actor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensecommunication',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'sent'), (2, 'received'), (3, 'bounced'), (4, 'failed')]),
        ),
    ]
