# Generated by Django 6.0.1 on 2026-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_licensedocument_unique_current_doc_per_license_actor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedocument',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'document'), (2, 'license'), (3, 'permit')]),
        ),
    ]
