# Generated by Django 6.0.1 on 2026-02-19 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0007_alter_licensecommunication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensedocument',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'document'), (2, 'license'), (3, 'permit')]),
        ),
        migrations.CreateModel(
            name='PermitDnr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dnr_number', models.CharField(max_length=64)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='licensing_p_is_acti_eb141a_idx')],
                'constraints': [models.UniqueConstraint(fields=('starts_at',), name='unique_permit_dnr_starts_at')],
            },
        ),
    ]
