# Generated by Django 6.0.3 on 2026-10-01 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0007_alter_license_ends_at_alter_license_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licenserelation',
            name='unique-mednr-for-license',
        ),
        migrations.RenameField(
            model_name='licenserelation',
            old_name='mednr',
            new_name='associate_number',
        ),
        migrations.AddConstraint(
            model_name='licenserelation',
            constraint=models.UniqueConstraint(fields=('associate_number', 'license'), name='unique-associate-number-for-license'),
        ),
    ]
