# Generated by Django 6.0.3 on 2026-10-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0008_remove_licenserelation_unique_mednr_for_license_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licensesequence',
            old_name='mnr',
            new_name='license_number',
        ),
    ]
