# Generated by Django 6.0.1 on 2026-03-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0008_actor_birth_year_alter_licensedocument_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserelation',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'ringer'), (2, 'associate ringer'), (3, 'associate'), (4, 'communication')]),
        ),
    ]
