# Generated by Django 6.0.1 on 2026-03-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0009_alter_licenserelation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserelation',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'ringer'), (2, 'associate-ringer'), (3, 'affiliate'), (4, 'communication')]),
        ),
    ]
