# Generated by Django 6.0.1 on 2026-03-03 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0010_alter_licenserelation_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licensedocument',
            name='unique_current_doc_per_license_actor_type',
        ),
        migrations.AddField(
            model_name='license',
            name='documents',
            field=models.ManyToManyField(blank=True, to='licensing.licensedocument'),
        ),
        migrations.AddField(
            model_name='licensedocument',
            name='is_permanent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licensesequence',
            name='latest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='licensing.license'),
        ),
        migrations.RemoveField(
            model_name='licensedocument',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='licensedocument',
            name='license',
        ),
    ]
