# Generated by Django 6.0.3 on 2026-03-16 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0011_remove_licensedocument_unique_current_doc_per_license_actor_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedocument',
            name='license_sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='licensing.licensesequence'),
        ),
        migrations.AddConstraint(
            model_name='licensedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_permanent', False)), fields=('license_sequence', 'actor', 'type', 'fingerprint'), name='unique_document_per_license_sequence__actor__type__fingerprint'),
        ),
    ]
