#!/bin/sh -

# This script initializes a PostgreSQL database with specific users and
# permissions.

set -u

. "$DB_ENV_FILE" || exit

psql -v ON_ERROR_STOP=1 \
	--username "$POSTGRES_USER" \
	--dbname "$POSTGRES_DB" <<-SQL
	CREATE DATABASE $DB_NAME;

	\c $DB_NAME

	-- Roles
	CREATE USER $DB_USER_RW WITH PASSWORD '$DB_PASS_RW';
	CREATE USER $DB_USER_RO WITH PASSWORD '$DB_PASS_RO';

	-- Basic connect
	GRANT CONNECT ON DATABASE $DB_NAME TO $DB_USER_RW, $DB_USER_RO;

	-- RW: full control over public schema
	GRANT USAGE, CREATE ON SCHEMA public TO $DB_USER_RW;
	ALTER DEFAULT PRIVILEGES FOR ROLE $DB_USER_RW IN SCHEMA public
		GRANT ALL PRIVILEGES ON TABLES TO $DB_USER_RW;
	ALTER DEFAULT PRIVILEGES FOR ROLE $DB_USER_RW IN SCHEMA public
		GRANT ALL PRIVILEGES ON SEQUENCES TO $DB_USER_RW;

	-- RO: strictly SELECT
	GRANT USAGE ON SCHEMA public TO $DB_USER_RO;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO $DB_USER_RO;
	ALTER DEFAULT PRIVILEGES FOR ROLE $DB_USER_RO IN SCHEMA public
		GRANT SELECT ON TABLES TO $DB_USER_RO;
SQL
